parameters:
    env(SECURITY_LOGIN_URL): 'http://localhost'
    env(SECURITY_TARGET_PATH_PARAMETER): 'redirect_url'
    security.login_url: '%env(SECURITY_LOGIN_URL)%'
    security.target_path_parameter: '%env(SECURITY_TARGET_PATH_PARAMETER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Security\:
        resource: '%kernel.project_dir%/src/Security'

    App\Security\RedirectUrlAuthenticationEntryPoint:
        arguments:
            $loginUrl: '%security.login_url%'
            $targetPathParameter: '%security.target_path_parameter%'