version: "3.9"
services:
  traefik:
    image: traefik:2.10
    command:
      --providers.docker=true
      --providers.docker.exposedByDefault=false
      --entryPoints.http.address=:80
    ports:
      - "80:80"
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public

  api:
    build:
      context: api/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./api:/app
    networks:
      - traefik-public
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.api.rule=Host(`api.localhost`)
      - traefik.http.routers.api.entryPoints=http
      - traefik.http.services.api.loadBalancer.server.port=80

  api-php-fpm:
    build:
      context: api/docker
      dockerfile: development/php-fpm/Dockerfile
    environment:
      APP_ENV: dev
      APP_SECRET: 67367feebda9e66879e58cadfe2f1c1b
      PHP_IDE_CONFIG: serverName=API
    volumes:
      - ./api:/app

  api-php-cli:
    build:
      context: api/docker
      dockerfile: development/php-cli/Dockerfile
    environment:
      APP_ENV: dev
      APP_SECRET: 67367feebda9e66879e58cadfe2f1c1b
    volumes:
      - ./api:/app

  api-postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - api-postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

volumes:
  api-postgres:

networks:
  traefik-public:
    name: traefik-public