# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    validation:
        email_validation_mode: strict

    #esi: true
    #fragments: true
    php_errors:
        log: true
        
    property_info:
        enabled: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
