framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        #failure_transport: failed

        # The bus that is going to be injected when injecting MessageBusInterface
        default_bus: default.bus

        buses:
            default.bus:

            command.bus:
                middleware:
                    - App\Infrastructure\Bus\Symfony\Middleware\ValidationMiddleware
                    - router_context

            query.bus:
                middleware:
                    - App\Infrastructure\Bus\Symfony\Middleware\ValidationMiddleware

            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - router_context

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            commands: '%env(MESSENGER_COMMANDS_TRANSPORT_DSN)%'
            events: '%env(MESSENGER_EVENTS_TRANSPORT_DSN)%'
            queries: '%env(MESSENGER_QUERIES_TRANSPORT_DSN)%'

        routing:
            App\Contracts\Bus\Command\CommandInterface: commands
            App\Contracts\Bus\Event\EventInterface: events
            App\Contracts\Bus\Query\QueryInterface: queries

when@test:
    framework:
        messenger:
            transports:
                events: 'in-memory://?serialize=true'
