parameters:
    feature_toggle.features: { }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\FeatureToggle\:
        resource: '%kernel.project_dir%/src/FeatureToggle'

    App\FeatureToggle\Features:
        arguments:
            $features: '%feature_toggle.features%'